Add missiing RAD logo
balancer-labs/assets pull request #217
Opened 2021-02-23 13:16 UTC by xla

In our initial PR #207 we missed to add the asset itself. I wasn't able to get the generated files updated. Will that happen in another step? Let me know if anything is missing.

Signed-off-by: Alexander Simmerl <a.simmerl@gmail.com>

2021-02-23 22:49 UTC, EndymionJkb commented
I believe the address has to be lower-case (not the checksum version)

2021-02-24 02:20 UTC, rabmarut requested changes
Yes, please change the file name to all lowercase and then we can approve.

2021-02-24 08:22 UTC, xla commented
Thanks for the quick feedback! I lowercased and regenerated. Let me know if there is anything else stopping this from going in. Can also stash the changes if you'd prefer a single clean commit.

2021-02-24 14:02 UTC, rabmarut approved these changes

2021-02-24 14:02 UTC, merged